title: Learn DMN in 15 minutes
author: Guilherme Carreiro
email: karreiro@gmail.com
description: >
  Learn DMN in 15 minutes
baseurl: ''
url: 'http://learn-dmn-in-15-minutes.com'
google_analytics: 'UA-160845171-1'
markdown: kramdown
version: 2.0.0
